apiVersion: object.rook-s3-nano/v1alpha1
kind: ObjectStore
metadata:
  name: objectstore-sample
spec:
  image: quay.ceph.io/ceph-ci/ceph:wip-librados-wrapper-7
  volumeClaimTemplate:
    spec:
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
